### ISSUE TITLE
Make dates in the CPAN::Changes::Spec format

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/module-release#4]

**Comment by paultcochrane** [comment]
I started to have a look at this and it seems that dates are already output in `CPAN::Changes::Spec` format (at least, as implemented in `script/release`.  Or is it perhaps that you want a specific method which encapsulates this behaviour which can then be called in the release script?

**Comment by briandfoy** [comment]
I think a get_release_date method that abstracts it would be nice.

**Comment by paultcochrane** [comment]
I've added a `get_release_date` method in PR #28.  I've used `DateTime` as the implementation felt simpler.  If you want me to change anything just let me know and I'll update and resubmit.

**Comment by briandfoy** [comment]
It would be nice to use something lighter than DateTime, but it's fine for now. Closing. Thanks!
