### ISSUE TITLE
version numbers need to re-assemble with the same significant digits

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/module-release#5]
Right now it assumes two decimal places, changing 1.001 to 1.01

**Comment by paultcochrane** [comment]
As mentioned in #25, it seems that this is no longer an issue, however I'm probably looking in the wrong location.  Is this still an issue?  If so, where is it appearing?

**Comment by briandfoy** [comment]
Perhaps there can be tests for that. I don't remember if I completely solved the problem.
