### ISSUE TITLE
[feature request] "requires" entry in .releaserc

### ISSUE THREAD

**Issue by Tux** [briandfoy/module-release#6]
with close to 200 available perl versions to test a module against, my .releaserc looks somewhat like this:

--8<---
cpan_user HMBRAND
automated_testing 1
skip_kwalitee 1
skip_manifest 1
skip_prereqs 1
skip_dist 1
allow_glob_in_perls 1
perls /pro/bin/perl:/usr/bin/perl\
:/media/Tux/perls/bin/perl5.6.[12]\
:/media/Tux/perls/bin/perl5.8._\
:/media/Tux/perls/bin/perl5.1[02468]_\
:/media/Tux/perls/bin/perl5.2[02468]_\
:/media/Tux/perls/bin/perl5.21._\
:/media/Tux/perls/bin/tperl5.6.2\
:/media/Tux/perls/bin/tperl5.8._\
:/media/Tux/perls/bin/tperl5.1[02468]_\
:/media/Tux/perls/bin/tperl5.2[02468]_\
:/media/Tux/perls/bin/tperl5.21._\
:/media/Tux/perls/bin/cperl5.2[01].*
-->8---

If a module depends on something else, like DBI, there is currently no way to tell Module::Release to skip a perl if that install does not have that module installed.

Would it be possible to have a line like

requires DBI,Data::Peek

and have Module::Release skip that perl if those modules are not installed?

**Comment by briandfoy** [comment]
I think a better way is to intercept a return value of a Makefile.PL or Build.PL when one of those checks for dependencies.

Alternately, have Module::Release look at those files to get the dependencies and check for them. But, if you want to test against a particular perl, I think most people would want Module::Release to fail for a perl that couldn't go through all the steps. 

I think you might want to think about generating the .releaserc so it only has the perls you want to test against, perhaps by going through all of them and selecting the ones that have the right modules installed.

**Comment by Tux** [comment]
I wanted it again, probably for the same reason, how about this:
``` diff
--- /pro/bin/release-lx09       2018-02-28 09:26:38.000000000 +0100
+++ /pro/bin/release    2018-05-20 14:26:06.220299811 +0200
@@ -373,6 +373,7 @@ $release->load_mixin( 'Module::Release::

 my $skip_prereqs = $opts{p} || $release->config->skip_prereqs;
 my $skip_dist    = $opts{D} || $release->config->skip_dist;
+my $required     =             $release->config->required || "";

 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 # Set automated testing from command line, config, environment, or default
@@ -393,11 +394,20 @@ $release->_debug( "Automated testing is
 unless( $opts{T} ) {
        my $old_perl = $release->get_perl;

-       foreach my $perl ( $release->perls ) {
+       PERL: foreach my $perl ( $release->perls ) {
                $release->_print("============Testing with $perl\n");
                $release->set_perl( $perl ) or next;

                $release->clean;
+
+               foreach my $mod ( grep m/\S/ => split m/\s*,\s*/ => $required ) {
+                       system "$perl -M$mod -e1 >/dev/null 2>&1";
+                       if( $? ) {
+                               warn "Prereq $mod not available\n";
+                               next PERL;
+                               }
+                       }
+
                $release->build_makefile;
                $release->make;
                $release->test;
```
And my entry in .releaserc:
```
⋮
skip_dist 1
allow_glob_in_perls 1
required DBI,Text::CSV_XS,SQL::Statement
perls /pro/bin/perl:/usr/bin/perl\
:/media/Tux/perls/bin/perl5.8.9\
:/media/Tux/perls/bin/perl5.10.1\
⋮
```
The "most people" argument is not affected, as it is an extra line in .releaserc. It is not default. It is by choice.

**Comment by briandfoy** [comment]
Yeah, okay. Send me a pull request and I'll merge it.

**Comment by briandfoy** [comment]
This was #34, but I never closed this issue.
